version: '2' 

services:

  spark-master:
    image: bde2020/spark-master:${SPARK_MASTER_VERSION:-3.0.1-hadoop3.2}
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment: 
      - PYSPARK_PYTHON=python3
    env_file:
      - ./spark.env
    volumes: 
      - ./Data:/Data
      - ./Producer:/Producer
    networks:
      - batch_network
   
  spark-worker1:
    image: bde2020/spark-worker:${SPARK_WORKER_VERSION:-3.0.1-hadoop3.2}
    container_name: spark-worker1
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8081:8081
    env_file:
      - ./spark.env
    networks:
      - batch_network
  
  spark-notebook:
    image: jupyter/all-spark-notebook
    container_name: spark-notebook
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=my-secret-token
      - SPARK_OPTS='--master=spark://spark-master:7077'
      - PYSPARK_PYTHON=python3
    ports:
      - "8889:8888"
    volumes:
      - ../notebook:/home/notebook
    networks:
      - batch_network
networks:
  batch_network:
    external: true